config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations"}

  resources :stats do
    collection do
      get 'heatmap'
      get 'topn'
      get 'players'
    end
  end

  get 'checkout/show'
  get 'welcome/index'

  resources :plays do
    collection do
      get 'history'
      post 'undo'
    end
  end

  resources :players

  resources :games do
    collection do
      get 'sorting'
    end
  end

  root 'welcome#index'

  resources :users
end

app/models/game.rb
class Game < ApplicationRecord
#  has_many :games_stats
  has_paper_trail ignore: [:state]
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def show
    @game = Game.find(params[:id])
  end

  def index
    @games = Game.all
  end

  def new
    @players = Player.all
  end

  def create
    game = Game.new
    game.num_legs = params[:game]["num_legs"]
    game.num_sets = params[:game]["num_sets"]
    game.players = params[:game]["players"].join(',')
    game.num_players = params[:game]["players"].count
    game.state = 'new'
    game.game_type = params[:game]["game_type"]
    game.points =  params[:game]["points"]
    game.score = Array.new(game.num_players, params[:game]["points"]).join(',')
    game.finish_type = params[:game]["finish_type"].map(&:to_i).sum
    game.player_won = 0
    game.save

    play = Play.new
    play.game_id = game.id
    play.num_set = 1
    play.num_leg = 1
    play.turn = 1
    play.player = params[:game]["players"].first
    play.dart1 = 0
    play.dart2 = 0
    play.dart3 = 0
    play.save

    game.play_id = play.id
    game.save

    params[:game]["players"].each do |id|
      stat = GamesStat.new
      stat.game_id = game.id
      stat.player_id = id
      stat.total_points = 0
      stat.total_darts = 0
      stat.max_score = 0
      stat.save
    end

    redirect_to :controller => 'games', :action => 'show', :id => game.id
  end

  def destroy
    @game = Game.find(params[:id])
    GamesStat.where(game_id: @game.id).delete_all
    Play.where(game_id: @game.id).delete_all
    @game.destroy

    redirect_to :controller => 'games', :action => 'index'
  end

  def sorting
    game = Game.find(params[:id])
    new_order = game.players.split(',').shuffle
    game.players = new_order.join(',')
    game.save
    play = Play.find_by(game_id: game.id)
    play.player = new_order[0].to_i
    play.save
    
    redirect_to :controller => 'games', :action => 'show', :id => params[:id]
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/index.html.erb
<h1>Список всех игр</h1>

<% all_games = Game
             .joins('LEFT JOIN games_stats ON games.id = games_stats.game_id')
             .joins('LEFT JOIN players ON games_stats.player_id = players.id')
             .select('games.id as game_id,
                      players.id as player_id,
                      players.name as player_name,
                      games.points-games_stats.total_points as points,
                      games.player_won as player_won,
                      games.state as state'
                    ) %>
  <% result = all_games.collect{|x| [x.game_id, x.player_id, x.player_name, x.points]}.group_by{|x| x[0]} %>

  <table class="table table-hover table-sm">
    <thead class="thead-dark">
      <tr>
        <th>Игроки</th>
        <th>Тип</th>
        <th>Очки</th>
        <th>Счёт</th>
        <th>Статус</th>
      </tr>
    </thead>

    <% @games.each do |game| %>
      <% head, *tail = result[game.id] %>
      <% temp = head.zip(*tail) %>
      <tr class='clickable-row' data-href='<%= game_path(game) %>' style='cursor: pointer'>
        <td>
          <% temp[2].each_with_index do |name,index| %>
            <% if temp[1][index] == game.player_won %>
              <b><%= name %></b>
            <% else %>
              <%= name %>
            <% end %>
          <% end %>
        </td>
        <td><%= game.game_type %></td>
        <td><%= game.points %></td>
        <td><%= temp[3].join(",") %></td>
        <td><%= game.state %></td>
      </tr>
    <% end %>
  </table>

<script type="text/javascript">
  jQuery(document).ready(function($) {
    $(".clickable-row").click(function() {
      window.location = $(this).data("href");
    });
  });
</script>

app/views/games/new.html.erb
<h1>Новая игра</h1>
<%= form_with scope: :game, url: {action: "create"}, local: true do |form| %>

  <h0>Выберите игроков:</h0>
  <% @players.each do |player| %>
    <li>
      <%= form.check_box :players, { multiple: true }, player.id, false %>
      <%= player.name %>
    </li>
  <% end %>

  <br></br>

  <h0>Тип игры:</h0>
  <%= form.select(:game_type) do %>
    <% [['X01', 'X01'], ['Cricket', 'Cricket'],['Eleven', 'Eleven']].each do |c| -%>
      <%= content_tag(:option, c.first, value: c.last) %>
    <% end %>
  <% end %>

  <br></br>

  <h0>Кол-во очков X01:</h0>
  <%= form.select(:points) do %>
    <% [['501', 501], ['401', 401], ['301', 301], ['201', 201], ['101', 101]].each do |c| -%>
      <%= content_tag(:option, c.first, value: c.last) %>
    <% end %>
  <% end %>

  <br></br>

  <h0>Тип закрытия:</h0>
  <% [[ 1, 'любой сектор', false],
      [ 2, 'последний дротик double', false],
      [ 4, 'последний дротик triple', false],
      [ 8, 'любой дротик double', true],
      [16, 'любой дротик triple', false],
     ].each do |f| %>
    <li>
      <%= form.check_box :finish_type, { multiple: true, checked: f[2] }, f[0], false %>
      <%= f[1] %>
    </li>
  <% end %>

  <br></br>

  <h0>Кол-во сетов:</h0>
  <%= form.number_field(:num_sets, min: 1, max: 20, step: 1, value: 1) %>

  <br></br>

  <h0>Кол-во игр в сете:</h0>
  <%= form.number_field(:num_legs, min: 1, max: 50, step: 1, value: 1) %>

  <br></br>

  <p>
    <%= form.submit "Создать"%>
  </p>
<% end %>

app/views/games/show.html.erb
  <% @play = Play.find(@game.play_id) %>

  <div class="row">
    <div class="col-sm">
      <strong>Тип игры:</strong>
      <%= @game.game_type %>
      <% if @game.game_type == "X01" %>
          <strong>до очков:</strong>
          <%= @game.points %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm">
      <strong>Партия:</strong>
      <%= @play.num_leg %>
      <strong>из</strong>
      <%= @game.num_legs %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm">
      <strong>Сет:</strong>
      <%= @play.num_set %>
      <strong>из</strong>
      <%= @game.num_sets %>
    </div>
  </div>

  <% curr_player_score = 0 %>
  <table id="game_table" class="table table-striped table-sm">
    <thead class="thead-dark">
      <tr>
        <th class="text-left">игрок</th>
        <th class="text-right">очки</th>
        <th class="text-right">1dart avg</th>
        <th class="text-right">3darts avg</th>
        <th class="text-right">максимум</th>
      </tr>
    </thead>
    <tbody>
      <% count = 0 %>
      <% @game.players.split(',').map(&:to_i).each do |id| %>
        <% curr_score = @game.score.split(',')[count].to_i %>
      <tr>
        <td>
          <% player = Player.find(id) %>
          <% if player.id == @play.player %>
            <% curr_player_score = curr_score %>
          <% end %>
          <%= player.name %>
        </td>
        <td align="right">
          <%= curr_score %>
        </td>
        <% stat = GamesStat.find_by(game_id: @game.id, player_id: id) %>
        <td align="right">
          <% if stat.total_darts != 0 %>
            <%= sprintf('%.2f', stat.total_points.to_f / stat.total_darts)  %>
          <% else %>
            <%= 0 %>
          <% end %>
        </td>
        <td align="right">
          <% if stat.total_darts != 0 %>
            <%= sprintf('%.2f', 3 * stat.total_points.to_f / stat.total_darts) %>
          <% else %>
            <%= 0 %>
          <% end %>
        </td>
        <td align="right">
          <%= stat.max_score %>
        </td>
      </tr>
      <% count = count + 1 %>
      <% end %>
    </tbody>
  </table>
  <div align="center">
    <%= link_to 'Назад', games_path, class: "btn btn-secondary btn-sm" %>
    <%= link_to 'История бросков', {:controller => "plays", :action => "history", :id => @game.id}, class: "btn btn-secondary btn-sm" %>
    <% if @game.state == "new" %>
      <%= link_to 'Перемешать игроков', sorting_games_path(:id => @game.id), class: "btn btn-secondary btn-sm" %>
    <% end %>
    <%=
      link_to 'Удалить', {:controller => "games", :action => "destroy", :id => @game.id},
                method: :delete,
                data: { confirm: 'Are you sure?' }, class: "btn btn-secondary btn-sm" %>
    <%= link_to 'Играть', {:controller => "plays", :action => "show", :id => @game.id}, class: "btn btn-secondary btn-sm" %>
  </div>

<% if @game.state != "new" %>
<script type="text/javascript">
$(document).ready(function() {
    $('#game_table').DataTable( {
      searching: false,
          bInfo: false,
         paging: false
    } );
} );
</script>
<% end %>