config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations"}

  resources :stats do
    collection do
      get 'heatmap'
      get 'topn'
      get 'players'
    end
  end

  get 'checkout/show'
  get 'welcome/index'

  resources :plays do
    collection do
      get 'history'
      post 'undo'
    end
  end

  resources :players

  resources :games do
    collection do
      get 'sorting'
    end
  end

  root 'welcome#index'

  resources :users
end

app/models/player.rb
class Player < ApplicationRecord
#  has_many :games_stats
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @players = Player.all
  end

  def show
    @player = Player.find(params[:id])
  end

  def new
  end

  def create
    @player = Player.new(params.require(:player).permit(:name))
    @player.save


    default_stat_code.each do |stat_code|
      player_stat = PlayerStat.new()
      player_stat.player_id = @player.id
      player_stat.stat_code = stat_code
      player_stat.stat_value = 0
      player_stat.save
    end

    redirect_to @player
  end

  def destroy
    if current_user.admin?
      @player = Player.find(params[:id])
      PlayerStat.where(player_id: @player.id).delete_all
      @player.destroy
    end

    redirect_to :controller => 'players', :action => 'index'
  end

  private
    def default_stat_code
      [
        'sector_miss', 'sector_25', 'sector_50',
        'sector_1', 'sector_2', 'sector_3', 'sector_4', 'sector_5', 'sector_6', 'sector_7', 'sector_8', 'sector_9', 'sector_10', 'sector_11', 'sector_12', 'sector_13', 'sector_14', 'sector_15', 'sector_16', 'sector_17', 'sector_18', 'sector_19', 'sector_20',
        'sector_D1', 'sector_D2', 'sector_D3', 'sector_D4', 'sector_D5', 'sector_D6', 'sector_D7', 'sector_D8', 'sector_D9', 'sector_D10', 'sector_D11', 'sector_D12', 'sector_D13', 'sector_D14', 'sector_D15', 'sector_D16', 'sector_D17', 'sector_D18', 'sector_D19', 'sector_D20',
        'sector_T1', 'sector_T2', 'sector_T3', 'sector_T4', 'sector_T5', 'sector_T6', 'sector_T7', 'sector_T8', 'sector_T9', 'sector_T10', 'sector_T11', 'sector_T12', 'sector_T13', 'sector_T14', 'sector_T15', 'sector_T16', 'sector_T17', 'sector_T18', 'sector_T19', 'sector_T20',
        'checkout_total',
	      'checkout_success',
        'checkout_maximum',
        'checkout_sum',
	      '1dart_sum',
	      '1dart_miss',
      	'1dart_throw',
      	'2dart_sum',
      	'2dart_miss',
      	'2dart_throw',
      	'3dart_sum',
      	'3dart_miss',
      	'3dart_throw',
      	'num_legs',
      	'num_sets',
      	'num_legs_won',
      	'num_sets_won',
      	'max_points',
        'points_60-99',
        'points_100-139',
        'points_140-179',
        'points_180'
      ]
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/index.html.erb
  <h1>Список игроков</h1>

  <table>
    <tr>
      <th>Имя</th>
      <th></th>
    </tr>

    <% @players.each do |player| %>
      <tr>
        <td><%= player.name %></td>
        <td><%= link_to 'Статистика', player_path(player) %></td>
        <td><%= link_to_if current_user.admin?, 'Удалить', player_path(player),
                method: :delete,
                data: { confirm: 'Уверены?' } %></td>
      </tr>
    <% end %>
  </table>

  <br></br>

  <%= link_to 'Новый игрок', new_player_path %>
  <%= link_to 'Назад', welcome_index_path %>

app/views/players/new.html.erb
<h1>Новый игрок</h1>
<%= form_with scope: :player, url: players_path,local: true do |form| %>
  <p>
    <%= form.label :Имя %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/players/show.html.erb
<%
  @games_stat = GamesStat.where(player_id: @player.id).order(:created_at).pluck(Arel.sql('created_at, printf("%.2f", 1.0*total_points / total_darts)'))
%>
<%= line_chart @games_stat %>


<% players_list = Player.all %>
<% @data_for_chart = players_list.map do |player|
  { name: player.name, data: GamesStat.where(player_id: player.id).order(:created_at).pluck(Arel.sql('created_at, printf("%.2f", 1.0*total_points / total_darts)')) }
end %>
<%= line_chart @data_for_chart  %>

<p>
  <strong>Имя:</strong>
  <%= @player.name %>
</p>
<p>
  <% if player_stat = PlayerStat.where(player_id: @player.id) %>
    <% fav_sector = Array.new %>
    <% fav_sector_count = 0 %>
    <% player_stat.each do |some_stat| %>
      <% case some_stat[:stat_code] %>
        <% when "1dart_sum" %>
          <% @dart1_sum = some_stat[:stat_value] %>
        <% when "2dart_sum" %>
          <% @dart2_sum = some_stat[:stat_value] %>
        <% when "3dart_sum" %>
          <% @dart3_sum = some_stat[:stat_value] %>
        <% when "1dart_miss" %>
          <% @dart1_miss = some_stat[:stat_value] %>
        <% when "2dart_miss" %>
          <% @dart2_miss = some_stat[:stat_value] %>
        <% when "3dart_miss" %>
          <% @dart3_miss = some_stat[:stat_value] %>
        <% when "1dart_throw" %>
          <% @dart1_throw = some_stat[:stat_value] %>
        <% when "2dart_throw" %>
          <% @dart2_throw = some_stat[:stat_value] %>
        <% when "3dart_throw" %>
          <% @dart3_throw = some_stat[:stat_value] %>
        <% when "max_points" %>
          <% @max_points = some_stat[:stat_value] %>
        <% when "points_60-99" %>
          <% @points_60_99 = some_stat[:stat_value] %>
        <% when "points_100-139" %>
          <% @points_100_139 = some_stat[:stat_value] %>
        <% when "points_140-179" %>
          <% @points_140_179 = some_stat[:stat_value] %>
        <% when "points_180" %>
          <% @points_180 = some_stat[:stat_value] %>
        <% when /^sector_(.*)/ %>
          <% if some_stat[:stat_value] > fav_sector_count %>
            <% fav_sector = [$1] %>
            <% fav_sector_count = some_stat[:stat_value] %>
          <% elsif some_stat[:stat_value] == fav_sector_count %>
            <% fav_sector.push($1) %>
          <% end %>
        <%
          when "num_legs"
            @num_legs = some_stat[:stat_value]
          when "num_legs_won"
            @num_legs_won = some_stat[:stat_value]
          when "num_sets"
            @num_sets = some_stat[:stat_value]
          when "num_sets_won"
            @num_sets_won = some_stat[:stat_value]
          when "checkout_total"
            @checkout_total = some_stat[:stat_value]
          when "checkout_success"
            @checkout_success = some_stat[:stat_value]
          when "checkout_maximum"
            @checkout_maximum = some_stat[:stat_value]
          when "checkout_sum"
            @checkout_sum = some_stat[:stat_value]
        %>
      <% end %>
    <% end %>
  <% end %>

<div class="col-6">
  <table class="table table-striped table-sm text-right" style="margin: 0px auto;">
    <caption style="caption-side: top; font-weight: bold;">Статистика по партиям/матчам</caption>
    <thead class="thead-dark">
      <tr>
        <th></th>
        <th>победа</th>
        <th>поражение</th>
        <th>ничья</th>
        <th>всего</th>
      </tr>
    </thead>
    <tbody>
      <% if @num_legs != 0 %>
      <tr>
        <td>
          партий
        </td>
        <td>
          <%= sprintf('%d (%d%%)', @num_legs_won, 100.0 * @num_legs_won / @num_legs) %>
        </td>
        <td>
          <%= sprintf('%d (%d%%)', @num_legs - @num_legs_won, 100.0 * (@num_legs - @num_legs_won) / @num_legs) %>
        </td>
        <td>
        </td>
        <td>
          <%= @num_legs %>
        </td>
      </tr>
      <tr>
        <td>
          матчей
        </td>
        <td>
          <%= sprintf('%d (%d%%)', @num_sets_won, 100.0 * @num_sets_won / @num_legs) %>
        </td>
        <td>
          <%= sprintf('%d (%d%%)', @num_sets - @num_legs_won, 100.0 * (@num_sets - @num_legs_won) / @num_sets) %>
        </td>
        <td>
        </td>
        <td>
          <%= @num_legs %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <table class="table table-striped table-sm text-right" style="margin: 0px auto;">
    <caption style="caption-side: top; font-weight: bold;">Статистика по дротикам</caption>
    <thead class="thead-dark">
      <tr>
        <th>#</th>
        <th>бросков</th>
        <th>очков</th>
        <th>промахов</th>
        <th>среднее</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td class="text-right">
          1
        </td>
        <td>
          <%= @dart1_throw %>
        </td>
        <td>
          <%= @dart1_sum %>
        </td>
        <td>
          <%= @dart1_miss %>
        </td>
        <td>
          <%= sprintf('%.2f', 1.0 * @dart1_sum / @dart1_throw) %>
        </td>
      </tr>
      <tr>
        <td class="text-right">
          2
        </td>
        <td>
          <%= @dart2_throw %>
        </td>
        <td>
          <%= @dart2_sum %>
        </td>
        <td>
          <%= @dart2_miss %>
        </td>
        <td>
          <%= sprintf('%.2f', 1.0 * @dart2_sum / @dart2_throw) %>
        </td>
      </tr>
      <tr>
        <td class="text-right">
          3
        </td>
        <td>
          <%= @dart3_throw %>
        </td>
        <td>
          <%= @dart3_sum %>
        </td>
        <td>
          <%= @dart3_miss %>
        </td>
        <td>
          <%= sprintf('%.2f', 1.0 * @dart3_sum / @dart3_throw) %>
        </td>
      </tr>

      <tfoot class="font-weight-bold">
        <tr>
          <td>
            всего
          </td>
          <td>
            <%= @dart1_throw + @dart2_throw + @dart3_throw %>
          </td>
          <td>
            <%= @dart1_sum + @dart2_sum + @dart3_sum %>
          </td>
          <td>
            <%= @dart1_miss + @dart2_miss + @dart3_miss %>
          </td>
          <td>
            <%= sprintf('%.2f', 1.0 * (@dart1_sum + @dart2_sum + @dart3_sum) / (@dart1_throw + @dart2_throw + @dart3_throw)) %>
          </td>
        </tr>
      </tfoot>
    </tbody>
  </table>

  <table class="table table-striped table-sm text-right" style="margin: 0px auto;">
    <caption style="caption-side: top; font-weight: bold;">Статистика по набранным очкам</caption>
    <thead class="thead-dark">
      <tr>
        <th class="w-75"></th>
        <th class="w-25"></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td align="right">
          в среднем с одного дротика:
        </td>
        <td align="left">
          <%= sprintf('%.2f', 1.0 * (@dart1_sum + @dart2_sum + @dart3_sum) / (@dart1_throw + @dart2_throw + @dart3_throw)) %>
        </td>
      </tr>
      <tr>
        <td align="right">
          в среднем с трех дротиков:
        </td>
        <td align="left">
          <%= sprintf('%.2f', 3.0 * (@dart1_sum + @dart2_sum + @dart3_sum) / (@dart1_throw + @dart2_throw + @dart3_throw))  %>
        </td>
      </tr>
      <tr>
        <td align="right">
          любимые сектора:
        </td>
        <td align="left">
          <%= fav_sector.join(' ') %>
        </td>
      </tr>
      <tr>
        <td align="right">
          максимальное кол-во очков за подход:
        </td>
        <td align="left">
          <%= @max_points %>
        </td>
      </tr>
      <tr>
        <td align="right">
          60 &rarr; 99:
        </td>
        <td align="left">
          <%= @points_60_99 %>
        </td>
      </tr>
      <tr>
        <td align="right">
          100 &rarr; 139:
        </td>
        <td align="left">
          <%= @points_100_139 %>
        </td>
      </tr>
      <tr>
        <td align="right">
          140 &rarr; 179:
        </td>
        <td align="left">
          <%= @points_140_179 %>
        </td>
      </tr>
      <tr>
        <td align="right">
          180:
        </td>
        <td align="left">
          <%= @points_180 %>
        </td>
      </tr>
    </tbody>
  </table>

  <table class="table table-striped table-sm text-right" style="margin: 0px auto;">
    <caption style="caption-side: top; font-weight: bold;">Статистика по закрытиям</caption>
    <thead class="thead-dark">
      <tr>
        <th class="w-75"></th>
        <th class="w-25"></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td align="right">
          всего попыток:
        </td>
        <td align="left">
          <%= @checkout_total %>
        </td>
      </tr>
      <tr>
        <td align="right">
          успешных:
        </td>
        <td align="left">
          <%= @checkout_success %>
        </td>
      </tr>
      <tr>
        <td align="right">
          процент успешных закрытий:
        </td>
        <td align="left">
          <%= sprintf('%.2f', 100.0 * @checkout_success / @checkout_total) %>
        </td>
      </tr>
      <tr>
        <td align="right">
          средний checkout:
        </td>
        <td align="left">
          <%= sprintf('%.2f', 1.0 * @checkout_sum / @checkout_success) %>
        </td>
      </tr>
      <tr>
        <td align="right">
          максимальный checkout:
        </td>
        <td align="left">
          <%= @checkout_maximum %>
        </td>
      </tr>
    </tbody>
  </table>

  <table class="table table-striped table-sm text-right" style="margin: 0px auto;">
    <caption style="caption-side: top; font-weight: bold;">Статистика по дротикам на партию</caption>
    <thead class="thead-dark">
      <tr>
        <th class="w-75"></th>
        <th class="w-25"></th>
      </tr>
    </thead>
    <tbody>
    <%
    @darts_stat = Game
      .where(player_won: @player.id)
      .joins('LEFT JOIN games_stats ON games_stats.game_id == games.id and games_stats.player_id == games.player_won')
      .pluck(Arel.sql('min(total_darts), max(total_darts), avg(total_darts)'))
    if @darts_stat %>
      <tr>
        <td align="right">
          минимум:
        </td>
        <td align="left">
          <%= @darts_stat[0][0] %>
        </td>
      </tr>
      <tr>
        <td align="right">
          максимум:
        </td>
        <td align="left">
          <%= @darts_stat[0][1] %>
        </td>
      </tr>
      <tr>
        <td align="right">
          среднее:
        </td>
        <td align="left">
          <%= sprintf('%.2f', @darts_stat[0][2].to_f) %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
</p>




<div id='darts_board'>
  <%= image_tag("winmau_blade_5.jpg", id: 'darts_board', size: "750x750", class: "align-self-start mr-3") %>
</div>
<div>
  <input type="checkbox" id="miss_matter" name="feature" value="miss_matter"  checked />
  <label for="miss_matter">С учетом промахов</label>
</div>

<%= link_to 'Назад', players_path %>

<script type="text/javascript">
  function draw_heatmap() {
    var miss_mater = 0;
    if (document.getElementById("miss_matter").checked) {
      miss_matter = 1
    };


    var heatmapInstance=h337.create({
      container: document.getElementById('darts_board')
    });

    $.ajax({
              type: "GET",
              url: "/stats/heatmap",
              data: {id: <%= @player.id %>, miss_matter: miss_matter},
              async: true,
              dataType: "json",
              success: function(response) {
                heatmapInstance.setData(response);
              },
              error: function () {
                alert("error");
              }
           });
  }

  draw_heatmap();
</script>